server:
  port: 8989


spring:
  application:
    name: gateway

# http://localhost:8989/user-service/users
# http://localhost:8989/company/companies
# http://localhost:8989/stock-exchange/stockexchanges
zuul:
  # host:
    # connect-timeout-millis: 2000
    # socket-timeout-millis: 5000
  routes:
    service_1:
      path: /user-service/**
      url: http://localhost:8081/
    service_2:
      path: /company/**
      url: http://localhost:8082/
    service_3:
      path: /stock-exchange/**
      url: http://localhost:8083/
      

jwt:
  secret: somesecretkey

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/